Mox.defmock(SkepticBot.MockHttpClient, for: SkepticBot.HttpClient)
Mox.defmock(SkepticBot.Podcasts.MockDownloadingWorker, for: SkepticBot.Podcasts.DownloadingWorker)
Mox.defmock(SkepticBot.MockTranscription, for: SkepticBot.Transcription)
Mox.defmock(SkepticBot.Storage.MockStorageProvider, for: SkepticBot.Storage.StorageProvider)
Mox.defmock(SkepticBot.Rag.MockEmbedding, for: SkepticBot.Rag.Embedding)
Application.put_env(:skeptic_bot, :http_client, SkepticBot.MockHttpClient)
Application.put_env(:skeptic_bot, :downloader_module, SkepticBot.Podcasts.MockDownloadingWorker)
Application.put_env(:skeptic_bot, :transcription_module, SkepticBot.MockTranscription)
Application.put_env(:skeptic_bot, :storage_provider, SkepticBot.Storage.MockStorageProvider)
Application.put_env(:skeptic_bot, :rag_embedding_module, SkepticBot.Rag.MockEmbedding)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(SkepticBot.Repo, :manual)
