Mox.defmock(SkepticBot.MockHttpClient, for: SkepticBot.HttpClient)
Mox.defmock(SkepticBot.MockDownloader, for: SkepticBot.Downloader)
Mox.defmock(SkepticBot.MockTranscriber, for: SkepticBot.Transcriber)
Mox.defmock(SkepticBot.Storage.MockStorageProvider, for: SkepticBot.Storage.StorageProvider)
Mox.defmock(SkepticBot.Rag.MockEmbedding, for: SkepticBot.Rag.Embedding)
Application.put_env(:skeptic_bot, :http_client, SkepticBot.MockHttpClient)
Application.put_env(:skeptic_bot, :downloader, SkepticBot.MockDownloader)
Application.put_env(:skeptic_bot, :transcriber, SkepticBot.MockTranscriber)
Application.put_env(:skeptic_bot, :storage_provider, SkepticBot.Storage.MockStorageProvider)
Application.put_env(:skeptic_bot, :rag_embedding_module, SkepticBot.Rag.MockEmbedding)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(SkepticBot.Repo, :manual)
